[package]
name = "imezx/warp"
version = "1.0.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["node_modules", "docs", ".github", "*.rbxl", "*.rbxmx", "*.rbxml"]
description = "A very-fast & powerful networking library for Roblox."

[dependencies]
